# Generated by Django 5.0.9 on 2025-11-03 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logistics", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionPaiement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("montant_ht", models.DecimalField(decimal_places=2, max_digits=10)),
                ("montant_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_frais",
                    models.CharField(
                        choices=[
                            ("MANUTENTION", "Manutention Portuaire"),
                            ("DOUANE", "Frais de Douane"),
                            ("STOCKAGE", "Frais de Stockage/Magasinage"),
                            ("AUTRES", "Autres Frais"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En Attente"),
                            ("REUSSI", "Réussi"),
                            ("ECHOUE", "Échoué"),
                            ("REMBOURSE", "Remboursé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("mode_paiement", models.CharField(blank=True, max_length=50)),
                (
                    "reference_externe",
                    models.CharField(
                        blank=True,
                        help_text="ID de transaction de la passerelle de paiement",
                        max_length=255,
                    ),
                ),
                ("date_heure_paiement", models.DateTimeField(auto_now_add=True)),
                (
                    "colis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="logistics.colis",
                    ),
                ),
                (
                    "utilisateur_payeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_effectues",
                        to="users.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de Paiement",
                "verbose_name_plural": "Transactions de Paiement",
            },
        ),
    ]
