# Generated by Django 5.0.9 on 2025-11-03 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Unique Colis",
                    ),
                ),
                (
                    "numero_bl",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Numéro de B/L (Bill of Lading)",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de la Marchandise"),
                ),
                (
                    "poids_kg",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Poids (kg)"
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Dimensions (L x l x H)",
                    ),
                ),
                (
                    "date_arrivee",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'Arrivée au Port"
                    ),
                ),
                (
                    "lieu_stockage",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Localisation Physique Actuelle",
                    ),
                ),
                (
                    "statut_actuel",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE_DECHARGE", "En Attente de Déchargement"),
                            ("EN_TRANSIT", "En Transit"),
                            ("DEDOUANEMENT", "En Dédouanement"),
                            ("PRET_RETRAIT", "Prêt au Retrait"),
                            ("LIVRE", "Livré/Retiré"),
                            ("LITIGE", "Litige/Problème"),
                        ],
                        default="EN_ATTENTE_DECHARGE",
                        max_length=30,
                        verbose_name="Statut Actuel",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colis_client",
                        to="users.utilisateur",
                        verbose_name="Client Propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colis",
                "verbose_name_plural": "Colis",
            },
        ),
        migrations.CreateModel(
            name="RetraitColis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_heure_retrait", models.DateTimeField(auto_now_add=True)),
                (
                    "preuve_identite_url",
                    models.URLField(
                        max_length=500,
                        verbose_name="Lien vers Preuve d'Identité Chiffrée",
                    ),
                ),
                (
                    "signature_client",
                    models.TextField(
                        help_text="Signature enregistrée du client ou de son mandataire.",
                        verbose_name="Signature Électronique (Base64)",
                    ),
                ),
                (
                    "agent_validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_retraits",
                        to="users.utilisateur",
                    ),
                ),
                (
                    "colis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrait_final",
                        to="logistics.colis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retrait de Colis",
                "verbose_name_plural": "Retraits de Colis",
            },
        ),
        migrations.CreateModel(
            name="SuiviStatut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE_DECHARGE", "En Attente de Déchargement"),
                            ("EN_TRANSIT", "En Transit"),
                            ("DEDOUANEMENT", "En Dédouanement"),
                            ("PRET_RETRAIT", "Prêt au Retrait"),
                            ("LIVRE", "Livré/Retiré"),
                            ("LITIGE", "Litige/Problème"),
                        ],
                        max_length=30,
                        verbose_name="Statut Enregistré",
                    ),
                ),
                (
                    "localisation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Localisation (GPS/Zone)",
                    ),
                ),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes Opérationnelles"),
                ),
                (
                    "agent_operationnel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_effectuees",
                        to="users.utilisateur",
                    ),
                ),
                (
                    "colis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_statuts",
                        to="logistics.colis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de Statut",
                "verbose_name_plural": "Suivis de Statut",
                "ordering": ["-date_heure"],
            },
        ),
    ]
