# Generated by Django 5.0.9 on 2025-11-05 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationDouaniere",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_declaration",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Numéro de Déclaration Officiel",
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("date_dedouanement", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumise à la Douane"),
                            ("CLEARED", "Dédouanée (Bon à Enlever)"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "documents_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        verbose_name="Lien vers Documents Douaniers",
                    ),
                ),
                (
                    "colis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration_douaniere",
                        to="logistics.colis",
                    ),
                ),
                (
                    "douanier",
                    models.ForeignKey(
                        limit_choices_to={"role__nom": "Douanier"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declarations_traitees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Douanier Traitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Déclaration Douanière",
                "verbose_name_plural": "Déclarations Douanières",
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant Total (XAF)",
                    ),
                ),
                ("date_emission", models.DateTimeField(auto_now_add=True)),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PENDING", "En Attente de Paiement"),
                            ("PAID", "Payée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "details_frais",
                    models.TextField(
                        blank=True,
                        verbose_name="Détails des frais (Stockage, Manutention, etc.)",
                    ),
                ),
                (
                    "colis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facture",
                        to="logistics.colis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
            },
        ),
    ]
