# Generated by Django 5.0.9 on 2025-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Adresse E-mail"
            ),
        ),
    ]
