# Generated by Django 5.0.9 on 2025-11-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        max_length=50,
                        verbose_name="Type d'Action (LOGIN_SUCCESS, MODIF_STATUT, etc.)",
                    ),
                ),
                (
                    "ressource_affectee",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nom de l'Entité Modifiée/Consultée",
                    ),
                ),
                (
                    "ressource_id",
                    models.CharField(
                        blank=True,
                        max_length=36,
                        verbose_name="UUID ou PK de la Ressource",
                    ),
                ),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        verbose_name="Détails (Anciennes/Nouvelles Valeurs, Erreurs)",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'Audit",
                "verbose_name_plural": "Journaux d'Audit",
                "ordering": ["-date_heure"],
            },
        ),
    ]
