"""
Django settings for transit project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import environ
from pathlib import Path
from datetime import timedelta
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4r2+6=l=k(n07q8h1psn-uk0qltx(l&159n5$locy0k6y)kv^#"

# Initialiser environ
# env = environ.Env()
# environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# IP autorisés
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "192.168.1.65",
    "192.168.2.147",
    "ngondetwilfrid.pythonanywhere.com",
]



AUTH_USER_MODEL = 'users.Utilisateur'


# Email Configuration using SMTP for sending emails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server host
EMAIL_PORT = 587  # SMTP server port
EMAIL_USE_TLS = True  # Whether to use TLS for SMTP (True/False)
EMAIL_USE_SSL = False  # Whether to use SSL for SMTP (True/False)
EMAIL_HOST_USER = 'esfaggabon@gmail.com'  # SMTP username (e.g., your_email@gmail.com)
EMAIL_HOST_PASSWORD = 'kptmdaqtyfartgjw'  # SMTP password


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-Party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',

    # Local Apps
    'users.apps.UsersConfig',
    'logistics.apps.LogisticsConfig',
    'payments.apps.PaymentsConfig',
    'audit.apps.AuditConfig', # Si vous avez créé cette app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "transit.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "transit.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]


LANGUAGE_CODE = "fr-fr"  # Langue par défaut

# Languages
LANGUAGES = [
    ("fr", _("Français")),
    ("en", _("English")),
]

TIME_ZONE = "Africa/Libreville"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# transit/settings.py

# ... (sous la section STATIC FILES, ou à la fin)

# -----------------------------------------------------------------
# FICHIERS MÉDIAS (Uploads utilisateurs, comme la preuve d'identité)
# -----------------------------------------------------------------

# URL publique utilisée pour accéder aux fichiers média (images, documents uploadés)
# Les images seront accessibles via http://127.0.0.1:8012/media/
MEDIA_URL = '/media/'

# Chemin absolu du système de fichiers vers le répertoire qui contiendra
# les fichiers uploadés par les utilisateurs.
# C'est dans ce dossier que Django va physiquement stocker les fichiers.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 
# -----------------------------------------------------------------

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Utilisation du JWT pour l'authentification
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # Sécurité par défaut: refus total, à lever au cas par cas
        'rest_framework.permissions.IsAuthenticated',
    ),
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # Permet l'utilisation de l'email comme identifiant
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}


# Sécurité en production
if not DEBUG:
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = "DENY"

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = False
    CSRF_COOKIE_HTTPONLY = False


# CORS Config
CORS_ALLOW_ALL_ORIGINS = True  # Ou configure des domaines spécifiques
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    "http://localhost:8012",  # Remplace par le domaine de ton frontend
    "http://192.168.1.65:8012",  # Remplace par le domaine de ton frontend
    "http://192.168.2.147:8012",  # Remplace par le domaine de ton frontend
    "ngondetwilfrid.pythonanywhere.com",
]
CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
]



# pppi_core/settings.py (Ajouts Celery)

# 1. Broker (Courtier) - URL de connexion à Redis ou RabbitMQ
# Exemple avec Redis (installé localement sur le port par défaut)
CELERY_BROKER_URL = 'redis://localhost:6379/0' 

# 2. Backend de Résultats (Pour stocker l'état et le résultat des tâches)
# Peut être le même que le broker ou la base de données
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# 3. Timezone (important pour les tâches planifiées)
CELERY_TIMEZONE = 'Africa/Libreville' # Ajustez si besoin

# 4. Sérialisation (JSON est le format le plus courant)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# 5. Tâches de Monitoring
CELERY_TASK_TRACK_STARTED = True



# Dans un terminal séparé:
# celery -A pppi_core worker -l info

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        # Ceci est la définition du schéma d'authentification JWT
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': (
                "Entrez votre token JWT au format: Bearer <TOKEN>"
            )
        }
    },
    # (Optionnel) Désactive l'authentification Basic si vous ne l'utilisez pas
    'USE_SESSION_AUTH': False,
}